version: "3"
services:
  postgres-challenge:
    image: postgres:16.0
    environment:
      POSTGRES_DB: challenge
      POSTGRES_USER: "arch"
      POSTGRES_PASSWORD: "challenge"
    ports:
      - "5432:5432"
    volumes:
      - volume-db-challenge:/var/lib/postgresql/data
    networks:
      - netChallenge
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - postgres-challenge
    networks:
      - netChallenge
volumes:
  volume-db-challenge:
  valume-api-challenge:

networks:
  netChallenge: