apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: fastburger-api-hpa
  namespace: fastburger-api
spec:
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 120
        type: Pods
        value: 1
      selectPolicy: Max
      stabilizationWindowSeconds: 300
    scaleUp:
      policies:
      - periodSeconds: 60
        type: Pods
        value: 2
      selectPolicy: Max
      stabilizationWindowSeconds: 60
  maxReplicas: 5
  metrics:
  - resource:
      name: cpu
      target:
        averageUtilization: 70
        type: Utilization
    type: Resource
  minReplicas: 2
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: api
