apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: fastburger-api
  labels:
    fastburger.service: volume-db-challenge
  name: volume-db-challenge
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
